version: "2"
services:  

  applications:
   image: tianon/true
   volumes:
     - ${APPS}:/var/www

  nginx:
    build: ./nginx
    volumes_from:
      - applications
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./nginx/sites/:/etc/nginx/sites-available
    ports:
      - 80:80
      - 443:443
    networks:
      - frontend
      - backend

  php-fpm:
    build:
      context: ./php-fpm
    volumes_from:
      - applications        
    volumes:
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
    expose:
      - 9000
    extra_hosts:
      - dockerhost:${DOCKER_HOST_IP}
    networks:
      - backend

networks:
  frontend:
  backend:
